FROM qicfan/qms-build-base:beta
ENV TZ=Asia/Shanghai
ENV PATH=/app:$PATH
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_USER=qms
ENV DB_PASSWORD=qms123456
ENV DB_NAME=qms
ENV DB_SSLMODE=disable

RUN addgroup -g 12331 qms && \
    adduser -D -u 12331 -G qms qms
RUN id qms
RUN echo 'qms ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN mkdir -p /dev/shm && chmod 1777 /dev/shm

WORKDIR /app

COPY QMediaSync .
COPY web_statics ./web_statics/
COPY scripts ./scripts/
COPY assets/db_config.html ./web_statics/
COPY icon.ico .
RUN chmod +x /app/scripts/docker-entrypoint.sh
RUN chmod +x /app/scripts/watch_update.sh
RUN chmod +x /app/QMediaSync
RUN chmod 777 /app

VOLUME ["/app/config", "/media"]

EXPOSE 12333
EXPOSE 8095
EXPOSE 8094
CMD ["/app/scripts/docker-entrypoint.sh"]
